(function(){
 const cms = loadCMS();
 window.NAMKEEN_CMS = cms;
 const root = document.documentElement;
 Object.entries(cms.theme||{}).forEach(([k,v])=>root.style.setProperty('--'+k,v));
 const qs=s=>document.querySelector(s), qsa=s=>document.querySelectorAll(s);
 const escHtml=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
 const toWaNumber=n=>{let d=String(n||'').replace(/[^0-9]/g,''); if(d.startsWith('0')) d='44'+d.slice(1); return d;};
 const waLink='https://wa.me/'+toWaNumber(cms.settings.whatsappNumber)+'?text='+encodeURIComponent(cms.settings.whatsappMessage||'');
 const setText=(sel,val)=>qsa(sel).forEach(el=>el.textContent=val);
 const sectionMap={hero:'#home',about:'#about',signature:'#signature',experience:'.premium-showcase',menu:'#menu',cta:'.cta',gallery:'#gallery',testimonials:'#testimonials',location:'#location',contact:'#contact'};
 Object.entries(sectionMap).forEach(([k,sel])=>{qsa(sel).forEach(el=>{ if(cms.sections && cms.sections[k]===false) el.style.display='none'; else el.style.display=''; });});
 document.title = `${cms.settings.brandName||'Namkeen'} ${cms.settings.brandSubtitle||''}`.trim();
 qsa('.brand img,.footer-logo').forEach(img=>img.src=cms.settings.logo);
 qsa('.loader-logo img').forEach(img=>img.src=cms.settings.loaderLogo || cms.settings.logo);
 const bStrong=qs('.brand-text strong'); if(bStrong) bStrong.textContent=cms.settings.brandName;
 const bSmall=qs('.brand-text small'); if(bSmall) bSmall.textContent=cms.settings.brandSubtitle;
 [['#home','navHome'],['#about','navAbout'],['#menu','navMenu'],['#gallery','navGallery'],['#location','navLocation'],['#contact','navContact']].forEach(([href,key])=>{qsa(`a[href="${href}"]`).forEach(a=>{if(!a.classList.contains('btn')) a.textContent=cms.settings[key]||a.textContent;});});
 qsa('a[href^="https://wa.me/"], .whatsapp-float').forEach(a=>{a.href=waLink; if(a.classList.contains('whatsapp-float')) return; if(a.textContent.includes('WhatsApp:')) a.textContent='WhatsApp: '+cms.settings.whatsappNumber; else a.textContent=cms.settings.orderButtonText || 'Order on WhatsApp';});
 qsa('a[href="#menu"].btn').forEach(a=>a.textContent=cms.settings.viewMenuButtonText || 'View Full Menu');
 const hero=qs('.hero'); if(hero){const img=hero.querySelector('img'); if(img) img.src=cms.settings.heroImage; const eye=hero.querySelector('.eyebrow'); if(eye) eye.textContent=cms.settings.heroEyebrow; const h=hero.querySelector('h1'); if(h) h.textContent=cms.settings.heroTitle; const p=hero.querySelector('p:not(.eyebrow)'); if(p) p.textContent=cms.settings.heroText;}
 const about=qs('#about'); if(about){const img=about.querySelector('img'); if(img) img.src=cms.settings.aboutImage; setText('#about .eyebrow',cms.settings.aboutEyebrow); setText('#about h2',cms.settings.aboutTitle); setText('#about .lead',cms.settings.aboutText); const boxes=about.querySelectorAll('.glass.p-3'); const fs=[[cms.settings.feature1Title,cms.settings.feature1Text],[cms.settings.feature2Title,cms.settings.feature2Text],[cms.settings.feature3Title,cms.settings.feature3Text]]; boxes.forEach((b,i)=>{if(fs[i]) b.innerHTML=`<b>${escHtml(fs[i][0])}</b><small class="d-block text-white-50">${escHtml(fs[i][1])}</small>`;});}
 const sig=qs('#signature'); if(sig){const cards=sig.querySelectorAll('.signature-card'); const data=[[cms.settings.signature1Title,cms.settings.signature1Text],[cms.settings.signature2Title,cms.settings.signature2Text],[cms.settings.signature3Title,cms.settings.signature3Text]]; cards.forEach((card,i)=>{const h=card.querySelector('h3'),p=card.querySelector('p'); if(h) h.textContent=data[i]?.[0]||h.textContent; if(p) p.textContent=data[i]?.[1]||p.textContent;});}
 const exp=qs('.premium-showcase'); if(exp){setText('.premium-showcase .eyebrow',cms.settings.experienceEyebrow); setText('.premium-showcase h2',cms.settings.experienceTitle); const lead=exp.querySelector('.lead,.text-white-50'); if(lead) lead.textContent=cms.settings.experienceText; const pts=exp.querySelectorAll('.experience-list span'); [cms.settings.experiencePoint1,cms.settings.experiencePoint2,cms.settings.experiencePoint3].forEach((v,i)=>{if(pts[i]) pts[i].textContent=v}); const imgs=exp.querySelectorAll('.showcase-grid img'); [cms.settings.experienceImage1,cms.settings.experienceImage2,cms.settings.experienceImage3].forEach((v,i)=>{if(imgs[i]&&v) imgs[i].src=v});}
 const menu=qs('#menu'); if(menu){setText('#menu .section-title .eyebrow',cms.settings.menuEyebrow); setText('#menu .section-title h2',cms.settings.menuTitle); const p=menu.querySelector('.section-title p.text-white-50'); if(p) p.textContent=cms.settings.menuText; const tabs=menu.querySelector('.menu-tabs'); if(tabs) tabs.innerHTML='<button class="active" data-filter="all">All</button>'+cms.categories.map(c=>`<button data-filter="${escHtml(c.slug)}">${escHtml(c.name)}</button>`).join(''); const row=menu.querySelector('.row.g-4'); if(row) row.innerHTML=cms.menu.map((m,i)=>{let cat=cms.categories.find(c=>c.slug===m.category)?.name||m.category; return `<div class="col-md-6 col-xl-4" data-aos="zoom-in" data-aos-delay="${(i%6)*50}" data-category="${escHtml(m.category)}"><article class="menu-card h-100 orderable-item" data-menu-name="${escHtml(m.name)}" data-menu-price="${escHtml(m.price)}" data-menu-category="${escHtml(cat)}"><span class="cat">${escHtml(cat)}</span><span class="price">${escHtml(m.price)}</span><h3>${escHtml(m.name)}</h3><p>${escHtml(m.desc)}</p><button type="button" class="add-cart-btn">Add to order</button></article></div>`}).join('');}
 const cta=qs('.cta'); if(cta){const img=cta.querySelector('img'); if(img) img.src=cms.settings.aboutImage; setText('.cta h2',cms.settings.ctaTitle); const p=cta.querySelector('p'); if(p) p.textContent=cms.settings.ctaText;}
 const gallery=qs('#gallery'); if(gallery){setText('#gallery .eyebrow',cms.settings.galleryEyebrow); setText('#gallery h2',cms.settings.galleryTitle); const wrap=gallery.querySelector('.swiper-wrapper'); if(wrap) wrap.innerHTML=(cms.gallery||[]).map((src,i)=>`<div class="swiper-slide"><img class="gallery-img glass p-1" data-aos="zoom-in" data-aos-delay="${(i%6)*50}" src="${escHtml(src)}"></div>`).join('');}
 const testimonials=qs('#testimonials'); if(testimonials){setText('#testimonials .eyebrow',cms.settings.testimonialsEyebrow||'Customer Reviews'); setText('#testimonials h2',cms.settings.testimonialsTitle||'What Our Guests Say'); const wrap=testimonials.querySelector('.testimonial-marquee-wrap'); if(wrap){const list=(cms.testimonials||[]).filter(t=>t.text); const fallback=[{rating:5,initials:'NR',name:'Guest',role:'Verified Guest',text:'Very tasty food. The garlic cheese naan, chicken and mutton biryani were really good. Ambience is beautiful and service is fast.'},{rating:5,initials:'NR',name:'Guest',role:'Verified Guest',text:'Fresh grill, generous portions and quick service. A proper Pakistani restaurant worth visiting again.'},{rating:5,initials:'NR',name:'Guest',role:'Verified Guest',text:'Great place for a casual meal with friends. Good prices, clean interior and friendly service.'},{rating:5,initials:'NR',name:'Guest',role:'Verified Guest',text:'Loved the interior, the lighting and the overall vibe. Food arrived hot and tasted amazing.'},{rating:5,initials:'NR',name:'Guest',role:'Verified Guest',text:'Perfect family dining place. The staff were welcoming and the food tasted fresh.'},{rating:5,initials:'NR',name:'Guest',role:'Verified Guest',text:'The mixed grill was full of flavour and the naan came fresh from the tandoor.'}]; const source=list.length?list:fallback; const makeCard=(t,i)=>{const rating=Number(t.rating||5); const safeRating=Math.max(1,Math.min(5,rating)); const stars='★'.repeat(safeRating)+'☆'.repeat(5-safeRating); return `<div class="review-card"><div class="review-copy"><div class="stars">${stars}</div><p>"${escHtml(t.text)}"</p></div><div class="review-meta"><span class="avatar alt${i%6}">${escHtml(t.initials||'NR')}</span><div><b>${escHtml(t.name||'Guest')}</b><small>${escHtml(t.role||'Verified Guest')}</small></div><em>Verified</em></div></div>`}; const normalize=(arr)=>{let a=arr.length?arr:source; while(a.length<6) a=a.concat(a); return a.slice(0,6);}; const topBase=normalize(source.filter((_,i)=>i%2===0)); const bottomBase=normalize(source.filter((_,i)=>i%2===1)); const groupTop=topBase.map(makeCard).join(''); const groupBottom=bottomBase.map(makeCard).join(''); wrap.innerHTML=`<div class="testimonial-lane"><div class="testimonial-track marquee-right">${groupTop}${groupTop}</div></div><div class="testimonial-lane"><div class="testimonial-track marquee-left">${groupBottom}${groupBottom}</div></div>`;}}
 const loc=qs('#location'); if(loc){setText('#location .eyebrow',cms.settings.mapEyebrow); setText('#location h2',cms.settings.mapTitle); const p=loc.querySelector('.section-title p'); if(p) p.textContent=cms.settings.address; const card=loc.querySelector('.location-card'); if(card){const h=card.querySelector('h3'); if(h) h.textContent=cms.settings.locationCardTitle; const cp=card.querySelector('p'); if(cp) cp.textContent=cms.settings.address; const a=card.querySelector('a'); if(a) a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(cms.settings.address||'');} const iframe=loc.querySelector('iframe'); if(iframe) iframe.src='https://www.google.com/maps?q='+encodeURIComponent(cms.settings.address||'')+'&output=embed';}
 const footer=qs('.footer'); if(footer){const ps=footer.querySelectorAll('p'); if(ps[0]) ps[0].textContent=cms.settings.footerText; const h3=footer.querySelectorAll('h3'); if(h3[0]) h3[0].textContent=cms.settings.quickLinksTitle; if(h3[1]) h3[1].textContent=cms.settings.contactTitle; if(h3[2]) h3[2].textContent=cms.settings.hoursTitle; const contactP=footer.querySelector('.col-lg-3:nth-child(3) p'); if(contactP) contactP.textContent=cms.settings.address; const hoursP=footer.querySelector('.col-lg-3:nth-child(4) p'); if(hoursP) hoursP.innerHTML=escHtml(cms.settings.openingHours).replace(/\n/g,'<br>'); const copy=footer.querySelector('.copyright'); if(copy) copy.textContent=cms.settings.copyrightText; const insta=footer.querySelector('.footer-instagram'); if(insta) insta.href=cms.settings.instagramUrl||'#'; const fb=footer.querySelector('.footer-facebook'); if(fb) fb.href=cms.settings.facebookUrl||'#';}
})();
